# interfaces.py
from typing import Protocol, List, Optional, Dict, Tuple
from models.entities import TaskItem, Project, Goal, ResourceItem, ReferenceItem, ResourceType
from services.repository import DraftItem # Needed for type hinting

# --- Interface for Feature F-01: Capture & Clarify ---
class InboxManager(Protocol):
    def get_inbox_items(self) -> List[str]: ...

    def add_to_inbox(self, text: str) -> None: ...
    def create_draft(self, text: str, classification: 'ClassificationResult') -> DraftItem: ...
    def apply_draft(self, draft: DraftItem, override_project_id: Optional[int] = None) -> None: ...
    def skip_inbox_item(self, item_text: str) -> None: ...
    # Legacy/Manual support
    def move_inbox_item_to_project(self, item_text: str, project_id: int, tags: List[str]) -> None: ...

# --- Interface for Feature F-02: Organize & Review ---
class GoalPlanner(Protocol):
    def get_all_goals(self) -> List[Goal]: ...

    def create_goal(self, name: str, description: str) -> Goal: ...

    def get_projects_for_goal(self, goal_id: str) -> List[Project]: ...

    def get_orphaned_projects(self) -> List[Project]: ...
    def add_manual_item(self, project_id: int, kind: str, name: str, **kwargs) -> None: ...
    def link_project_to_goal(self, project_id: int, goal_id: Optional[str]) -> None: ...

# --- Interface for Feature F-03: Engage ---
class TaskExecutor(Protocol):
    def get_next_actions(self, context_filter: Optional[str] = None) -> List[TaskItem]: ...
    def complete_item(self, item_id: str) -> None: ...
    def get_aggregated_shopping_list(self) -> Dict[str, List[Tuple[ResourceItem, str]]]: ...
    def toggle_resource_status(self, resource_id: str, is_acquired: bool) -> None: ...