# interfaces.py
from typing import Protocol, List, Optional
from models.entities import Task, Project, Goal, ProjectResource, ResourceType


# --- Interface for Feature F-01: Capture & Clarify ---
class InboxManager(Protocol):
    def get_inbox_items(self) -> List[str]: ...

    def add_to_inbox(self, text: str) -> None: ...

    def move_inbox_item_to_project(self, item_text: str, project_id: int, tags: List[str]) -> None: ...

    def create_project_from_inbox(self, item_text: str, new_project_name: str) -> None: ...

    def skip_inbox_item(self, item_text: str) -> None: ...


# --- Interface for Feature F-02: Organize & Review ---
class GoalPlanner(Protocol):
    def get_all_goals(self) -> List[Goal]: ...

    def create_goal(self, name: str, description: str) -> Goal: ...

    def get_projects_for_goal(self, goal_id: str) -> List[Project]: ...

    def get_orphaned_projects(self) -> List[Project]: ...

    # Updated for Resource Generalization
    def add_resource(self, project_id: int, name: str, r_type: ResourceType, store: str = "General") -> None: ...

    def add_reference_item(self, project_id: int, name: str, description: str) -> None: ...


# --- Interface for Feature F-03: Engage ---
class TaskExecutor(Protocol):
    def get_next_actions(self, context_filter: Optional[str] = None) -> List[Task]: ...

    def complete_task(self, project_id: int, task_id: int) -> None: ...

    def undo_complete_task(self, project_id: int, task_id: int) -> None: ...

    # Added for Shopping View
    def get_aggregated_shopping_list(self) -> dict[str, List[tuple[ProjectResource, str]]]: ...

    def toggle_resource_status(self, resource_id: str, is_acquired: bool) -> None: ...